add comment pr action template

diff --git a/.github/workflows/tf-lint-test.yaml b/.github/workflows/tf-lint-test.yaml
--- a/.github/workflows/tf-lint-test.yaml
+++ b/.github/workflows/tf-lint-test.yaml
@@ -20,6 +20,21 @@ env:
 jobs:
   lint-and-test:
     runs-on: ubuntu-20.04
+    outputs:
+      format_out: ${{ steps.fmt.outputs.stdout }}
+      format_err: ${{ steps.fmt.outputs.stderr }}
+      format_result: ${{ steps.fmt.outcome }}
+      init_out: ${{ steps.init.outputs.stdout }}
+      init_err: ${{ steps.init.outputs.stderr }}
+      init_result: ${{ steps.init.outcome }}
+      workspace_out: ${{ steps.workspace.outputs.stdout }}
+      workspace_err: ${{ steps.workspace.outputs.stderr }}
+      workspace_result: ${{ steps.workspace.outcome }}
+      validate_out: ${{ steps.validate.outputs.stdout }}
+      validate_err: ${{ steps.validate.outputs.stderr }}
+      validate_result: ${{ steps.validate.outcome }}
+      plan: "${{ steps.plan.outputs.stdout }}"
+      plan_result: ${{ steps.plan.outcome }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
@@ -57,111 +72,111 @@ jobs:
         id: plan
         run: terraform plan -var-file _${{ inputs.environment }}.json -no-color -lock-timeout=20s -out plan_${{ inputs.environment }}.out
 
-      - name: Comment on PR
-        uses: actions/github-script@v5
-        env:
-          format_out: ${{ steps.fmt.outputs.stdout }}
-          format_err: ${{ steps.fmt.outputs.stderr }}
-          init_out: ${{ steps.init.outputs.stdout }}
-          init_err: ${{ steps.init.outputs.stderr }}
-          workspace_out: ${{ steps.workspace.outputs.stdout }}
-          workspace_err: ${{ steps.workspace.outputs.stderr }}
-          validate_out: ${{ steps.validate.outputs.stdout }}
-          validate_err: ${{ steps.validate.outputs.stderr }}
-          plan: "${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const CODE_BLOCK = '```';
-            const fmt_result = '${{ steps.fmt.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
-            const init_result = '${{ steps.init.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
-            const validate_result = '${{ steps.validate.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
-            const workspace_result = '${{ steps.workspace.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
-            const plan_result = '${{ steps.plan.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
+      # - name: Comment on PR
+      #   uses: actions/github-script@v5
+      #   env:
+      #     format_out: ${{ steps.fmt.outputs.stdout }}
+      #     format_err: ${{ steps.fmt.outputs.stderr }}
+      #     init_out: ${{ steps.init.outputs.stdout }}
+      #     init_err: ${{ steps.init.outputs.stderr }}
+      #     workspace_out: ${{ steps.workspace.outputs.stdout }}
+      #     workspace_err: ${{ steps.workspace.outputs.stderr }}
+      #     validate_out: ${{ steps.validate.outputs.stdout }}
+      #     validate_err: ${{ steps.validate.outputs.stderr }}
+      #     plan: "${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const CODE_BLOCK = '```';
+      #       const fmt_result = '${{ steps.fmt.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
+      #       const init_result = '${{ steps.init.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
+      #       const validate_result = '${{ steps.validate.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
+      #       const workspace_result = '${{ steps.workspace.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
+      #       const plan_result = '${{ steps.plan.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
 
-            const output = `
-            ### ${ fmt_result } Terraform Format and Style 🎨
-            <details><summary>Logs</summary>
-            Output
+      #       const output = `
+      #       ### ${ fmt_result } Terraform Format and Style 🎨
+      #       <details><summary>Logs</summary>
+      #       Output
 
-            ${ CODE_BLOCK }diff
-            ${ process.env.format_out }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }diff
+      #       ${ process.env.format_out }
+      #       ${ CODE_BLOCK }
 
-            Errors
+      #       Errors
 
-            ${ CODE_BLOCK }
-            ${ process.env.format_err }
-            ${ CODE_BLOCK }
-            </details> <!-- End Format Logs -->
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.format_err }
+      #       ${ CODE_BLOCK }
+      #       </details> <!-- End Format Logs -->
 
-            ### ${ init_result } Terraform Initialization ⚙️
-            <details><summary>Logs</summary>
-            Output
+      #       ### ${ init_result } Terraform Initialization ⚙️
+      #       <details><summary>Logs</summary>
+      #       Output
 
-            ${ CODE_BLOCK }
-            ${ process.env.init_out }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.init_out }
+      #       ${ CODE_BLOCK }
 
-            Errors
+      #       Errors
 
-            ${ CODE_BLOCK }
-            ${ process.env.init_err }
-            ${ CODE_BLOCK }
-            </details> <!-- End Init Logs -->
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.init_err }
+      #       ${ CODE_BLOCK }
+      #       </details> <!-- End Init Logs -->
 
-            ### ${ validate_result } Terraform Validation 🤖
-            <details><summary>Logs</summary>
-            Output
+      #       ### ${ validate_result } Terraform Validation 🤖
+      #       <details><summary>Logs</summary>
+      #       Output
             
-            ${ CODE_BLOCK }
-            ${ process.env.validate_out }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.validate_out }
+      #       ${ CODE_BLOCK }
             
-            Errors
+      #       Errors
             
-            ${ CODE_BLOCK }
-            ${ process.env.validate_err }
-            ${ CODE_BLOCK }
-            </details> <!-- End Validate Logs -->
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.validate_err }
+      #       ${ CODE_BLOCK }
+      #       </details> <!-- End Validate Logs -->
 
-            ### ${ workspace_result } Terraform select Workspace 👈
-            <details><summary>Logs</summary>
-            Output
+      #       ### ${ workspace_result } Terraform select Workspace 👈
+      #       <details><summary>Logs</summary>
+      #       Output
             
-            ${ CODE_BLOCK }
-            ${ process.env.workspace_out }
-            ${ CODE_BLOCK }
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.workspace_out }
+      #       ${ CODE_BLOCK }
             
-            Errors
+      #       Errors
             
-            ${ CODE_BLOCK }
-            ${ process.env.workspace_err }
-            ${ CODE_BLOCK }
-            </details> <!-- End Workspace Logs -->
+      #       ${ CODE_BLOCK }
+      #       ${ process.env.workspace_err }
+      #       ${ CODE_BLOCK }
+      #       </details> <!-- End Workspace Logs -->
 
-            ### ${ plan_result } Terraform Plan 📖
-            <details><summary>Logs</summary>
+      #       ### ${ plan_result } Terraform Plan 📖
+      #       <details><summary>Logs</summary>
             
-            ${ CODE_BLOCK }terraform
-            ${ process.env.plan }
-            ${ CODE_BLOCK }
-            </details>
+      #       ${ CODE_BLOCK }terraform
+      #       ${ process.env.plan }
+      #       ${ CODE_BLOCK }
+      #       </details>
         
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
           
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-      - name: Terraform errored
-        if: |
-          steps.fmt.outcome == 'failure' ||
-          steps.init.outcome == 'failure' ||
-          steps.validate.outcome == 'failure' ||
-          steps.workspace.outcome == 'failure' ||
-          steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform errored
+      #   if: |
+      #     steps.fmt.outcome == 'failure' ||
+      #     steps.init.outcome == 'failure' ||
+      #     steps.validate.outcome == 'failure' ||
+      #     steps.workspace.outcome == 'failure' ||
+      #     steps.plan.outcome == 'failure'
+      #   run: exit 1
